In [1]:
import torch

In [2]:
d = data1 = torch.tensor([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [3]:
indices = torch.tensor([[[0,0], [1,0]],[[0,1], [1,1]]])

In [4]:
res = torch.gather(d, 1, indices)

In [5]:
res

tensor([[[1, 1],
         [2, 1]],

        [[3, 4],
         [4, 4]]])

In [6]:
d = data1 = torch.tensor([[1,1,1],[2,2,2]])

In [7]:
res = torch.stack((d[0, :], d[1, :]), dim=1)

In [8]:
res

tensor([[1, 2],
        [1, 2],
        [1, 2]])

In [9]:
d3 = data1 = torch.tensor([[[1,1,1],[2,2,2]], [[3,3,3],[4,4,4]]])
asd = torch.tensor([[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]], [[1.1, 1.2, 1.3], [1.4, 1.5, 1.6], [1.7, 1.8, 1.9]]])
asd2 = torch.tensor([[[2.1, 2.2, 2.3], [2.4, 2.5, 2.6], [2.7, 2.8, 2.9]], [[3.1, 3.2, 3.3], [3.4, 3.5, 3.6], [3.7, 3.8, 3.9]]])

cool_list = torch.stack((asd, asd2), dim=1)
print(cool_list)

tensor([[[[0.1000, 0.2000, 0.3000],
          [0.4000, 0.5000, 0.6000],
          [0.7000, 0.8000, 0.9000]],

         [[2.1000, 2.2000, 2.3000],
          [2.4000, 2.5000, 2.6000],
          [2.7000, 2.8000, 2.9000]]],


        [[[1.1000, 1.2000, 1.3000],
          [1.4000, 1.5000, 1.6000],
          [1.7000, 1.8000, 1.9000]],

         [[3.1000, 3.2000, 3.3000],
          [3.4000, 3.5000, 3.6000],
          [3.7000, 3.8000, 3.9000]]]])


In [10]:
resd3 = torch.stack((cool_list[:, 0], cool_list[:, 1]), dim=2)


In [16]:
resd3 = resd3.view(resd3.shape[0], resd3.shape[1], resd3.shape[2] * resd3.shape[3])

In [17]:
resd3

tensor([[[0.1000, 0.2000, 0.3000, 2.1000, 2.2000, 2.3000],
         [0.4000, 0.5000, 0.6000, 2.4000, 2.5000, 2.6000],
         [0.7000, 0.8000, 0.9000, 2.7000, 2.8000, 2.9000]],

        [[1.1000, 1.2000, 1.3000, 3.1000, 3.2000, 3.3000],
         [1.4000, 1.5000, 1.6000, 3.4000, 3.5000, 3.6000],
         [1.7000, 1.8000, 1.9000, 3.7000, 3.8000, 3.9000]]])

In [18]:
asd = torch.tensor([1,2,3,4,5,6,7,8])
temp = torch.tensor([2,4,6])
asd[temp]

tensor([3, 5, 7])

In [19]:
resd3.shape

torch.Size([2, 3, 6])

In [27]:
a = [[1,2], [0,1]]
a =torch.tensor(a)

In [28]:
resd3[a]

IndexError: index 2 is out of bounds for dimension 0 with size 2